title: LiLAB
# tagline: Here is personal website of Hanlin Cai. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: Two roads diverged in woods, I took the one less traveled by.
#Comment out url when working locally to resolve base urls correctly
url: https://usst-lilab.github.io/

# Owner/author information
owner:
  name: Wangyan Li
  avatar: Wangyanli.png
  bio: 副教授，硕士生导师，上海市青年东方学者
  email: Wangyan_Li@usst.edu.cn
  #cv: https://usst-lilab.github.io/file/CV.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  #twitter: lancecai2002
  linkedin: https://www.linkedin.com/in/wangyan-li-69794692?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app
  scholar: https://scholar.google.com/citations?user=UemwIpIAAAAJ
  redbook: https://www.xiaohongshu.com/user/profile/5fefb40a0000000001005894?xhsshare=WeixinSession&appuid=5fefb40a0000000001005894&apptime=1713936430
  #github: USST-LiLAB
  #bilibili: 594030035
  #researchgate: https://www.researchgate.net/profile/Hanlin-Cai
  #zhihu: https://www.zhihu.com/people/chlire
  # facebook: caihanlin2002
  # instagram: lancecai2002
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About US
    url: /
  - title: Our members
    url: /members/
  - title: Our Results
    url: /Results/
  - title: 实验区
    url: /实验区/
  - title: Seminar/讨论班
    url: /讨论班/
  - title: 学术交流
    url: /学术交流/
  - title: Downloads/资料下载
    url: /downloads/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]


analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-S0N3SCQNY3"
    anonymize_ip: false # default